### ISSUE TITLE
Migrate to ReScript syntax

### ISSUE THREAD

**Issue by MoOx** [rescript-react-native/rescript-react-navigation#42]
Blocked by https://github.com/rescript-lang/rescript-compiler/issues/5104 (if we want to use `bsb -format`).
Otherwise we should investigate if we could remove class (I have to admit I never really checked the reason, if they are mandatory or not and if we could rewrite bindings without using them - poke @cem2ran which wrote initial bindings in #20).

**Comment by MoOx** [comment]
They won't be added back into rescript syntax. I guess we could just use convert class type to records and external using `@send` if necessary.

**Comment by cem2ran** [comment]
I think this can be replaced with the object type spread from the latest version (9.1)

![20210507_150319.jpg](https://user-images.githubusercontent.com/959142/117453633-72e2c300-af45-11eb-9bd8-16dbe5f874c3.jpg)

**Comment by cem2ran** [comment]
@MoOx I did a quick test of my assumption. It does compile. Sooo it works right? :D I opened a draft PR.

**Comment by Freddy03h** [comment]
Hi @cem2ran ! I commented your PR, did you saw it?
